# Generated by Django 3.2.4 on 2022-12-10 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homerent', '0005_auto_20221210_1315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentsDetails',
        ),
    ]
