# Generated by Django 3.2.4 on 2022-12-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homerent', '0007_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('last_unit', models.IntegerField(max_length=7)),
                ('new_unit', models.IntegerField(max_length=7)),
                ('unit_consumed', models.IntegerField(max_length=7)),
                ('ebill_amt', models.IntegerField(max_length=7)),
                ('total_amount', models.IntegerField(max_length=7)),
                ('amount_paid', models.IntegerField(max_length=7)),
                ('balance', models.IntegerField(max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
