# Generated by Django 3.2.4 on 2022-12-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homerent', '0008_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdetails',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
