# Generated by Django 4.1.4 on 2022-12-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homerent', '0009_usersdetails_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('unit', models.IntegerField(max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
