# Generated by Django 4.1.4 on 2023-01-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homerent', '0012_alter_profile_balance_alter_profile_tarrif'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='room_rent',
            field=models.IntegerField(default=7000),
            preserve_default=False,
        ),
    ]
