# Generated by Django 4.1.4 on 2023-01-02 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homerent', '0013_profile_room_rent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersdetails',
            old_name='electricunit',
            new_name='bill_id',
        ),
    ]
