# Generated by Django 4.1.4 on 2023-01-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homerent', '0015_alter_usersdetails_bill_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('total_amount', models.IntegerField(max_length=7)),
                ('amount_paid', models.IntegerField(max_length=7)),
                ('balance', models.IntegerField(max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
