# Generated by Django 4.1.4 on 2023-01-02 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homerent', '0017_transaction_bill_id_transaction_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_transaction_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homerent.transaction'),
        ),
    ]
