# Generated by Django 4.1.4 on 2023-01-08 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homerent', '0019_bills_paid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersDetails',
            new_name='PaymentDetails',
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
