# Generated by Django 4.1.4 on 2023-01-08 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homerent', '0020_rename_usersdetails_paymentdetails_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bills',
            new_name='Bill',
        ),
        migrations.RenameModel(
            old_name='MeterReadings',
            new_name='MeterReading',
        ),
        migrations.RenameModel(
            old_name='PaymentDetails',
            new_name='PaymentDetail',
        ),
    ]
