# Generated by Django 4.1.4 on 2023-01-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homerent', '0021_rename_bills_bill_rename_meterreadings_meterreading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreading',
            name='units',
            field=models.IntegerField(default=7, max_length=7),
            preserve_default=False,
        ),
    ]
