# Generated by Django 4.1.4 on 2023-01-15 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homerent', '0022_meterreading_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meterreading',
            name='units',
        ),
    ]
