# Generated by Django 4.1.4 on 2023-01-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homerent', '0023_remove_meterreading_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='building',
            new_name='building_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='room_no',
            new_name='building_no',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='home_no',
            new_name='door_no',
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='unit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='paidamount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_paid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_amount',
            field=models.IntegerField(),
        ),
    ]
