# Generated by Django 4.1.4 on 2023-01-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homerent', '0024_rename_building_profile_building_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_no',
            field=models.IntegerField(null=True, verbose_name=range(6000000000, 9999999999)),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
