# Generated by Django 4.1.4 on 2023-01-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homerent', '0026_alter_profile_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_no',
            field=models.BigIntegerField(default=9876543210),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='scs', max_length=200),
            preserve_default=False,
        ),
    ]
