# Generated by Django 4.1.4 on 2023-01-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homerent', '0028_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
